# Generated by Django 5.2.12 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("processing", "В обработке"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
