# Generated by Django 5.2.12 on 2026-03-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="ID Telegram-группы для уведомлений о заказах",
                        max_length=100,
                        null=True,
                        verbose_name="ID admin-чата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки бота",
                "verbose_name_plural": "Настройки бота",
            },
        ),
        migrations.CreateModel(
            name="RequiredChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        help_text="@username или -100xxxxxxxxxx",
                        max_length=100,
                        verbose_name="ID канала",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название канала"),
                ),
                (
                    "invite_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка для вступления"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Обязательный канал",
                "verbose_name_plural": "Обязательные каналы",
            },
        ),
    ]
