# Generated by Django 5.2.12 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcasts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("ready", "Готово к отправке"),
                    ("sending", "Отправляется"),
                    ("sent", "Отправлено"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
